pipeline:
    build:
        image: rust
        commands:
            # Get dependencies are expected to be in a local folder.
            - git -C clone https://codeberg.org/libreda/iron-shapes
            - cargo check
            - cargo test
