[package]
name = "libreda-db"
version = "0.0.1"
authors = ["Thomas Kramer <code@tkramer.ch>"]
edition = "2018"
license = "AGPLv3"
description = "Layout and netlist datastructures for chip design."
readme = "README.md"
homepage = "https://libreda.org"
repository = "https://codeberg.org/libreda/libreda-db"

[dependencies]
log = "0.4"
itertools = "0.10.0"
iron-shapes = { path = "../iron-shapes" }
genawaiter = { version = "0.99.1", default-features = false }
